# Generated by Django 5.0.4 on 2024-04-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('PI', 'Piauí')], max_length=120)),
                ('cores', models.CharField(max_length=80)),
                ('ano_de_fundacao', models.PositiveIntegerField()),
                ('tem_mundial', models.BooleanField(default=True)),
            ],
        ),
    ]
