# Generated by Django 5.0.4 on 2024-04-04 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cores', models.CharField(blank=True, max_length=80, null=True)),
                ('ano_fundacao', models.PositiveIntegerField(default=0)),
                ('tem_mundial', models.BooleanField(default=False)),
                ('escudo', models.ImageField(null=True, upload_to='clubes')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clubes', to='comun.cidade')),
            ],
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
